# Site setting
blog_username: TiAmo
sex: girl
birthday: 2002.7
career: student
personal signature: 当我遇到你的那天，我希望是在意大利。
github_username:  qiaoan888
email: 3401617151@qq.com

  
baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
