# Site setting
title: TiAmo的博客
SEOTitle: TiAmo的博客
header-img:  
email: 3401617151@qq.com
description: 当我遇到你的那天，我希望是在意大利。
url: "https://qiaoan888.github.io"
baseurl: ""


# Sidebar settings
sidebar: true                          
sidebar-avatar: /img/avatar-by.JPG   



# SNS settings
RSS: true
weibo_username:     username
zhihu_username:     username
github_username:    qiaoan888
facebook_username:  username
jianshu_username:   jianshu_id




# Featured Tags
featured-tags: true                     
featured-condition-size: 0

